routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkpdController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UrusanController;
use App\Http\Controllers\BelanjaController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\KegiatanController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;

use App\Http\Controllers\PendapatanController;
use App\Http\Controllers\PerekeningController;
use App\Http\Controllers\ProgramskpdController;
use App\Http\Controllers\SubkegiatanController;
use App\Http\Controllers\RelpendapatanController;

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/auth', [LoginController::class, 'auth'])->name('auth')->middleware('guest');


Route::post('/logout', [LoginController::class, 'logout'])->middleware('auth');


Route::get('/regadmin', [RegisterController::class, 'index'])->middleware('guest');
Route::post('/regadmin', [RegisterController::class, 'store']);

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth');
Route::get('/data-json', [DashboardController::class, 'datajson'])->middleware('guest');
Route::get('/get-json', [DashboardController::class, 'getjson'])->middleware('guest');


Route::resource('/datauser', UserController::class)->middleware('admin');

Route::resource('/dataskpd', SkpdController::class)->middleware('admin');
Route::post('/importskpd', [SkpdController::class, 'importexcel'])->name('importexcel')->middleware('admin'); //tambah class skpd

Route::resource('/dataprogram', ProgramController::class)->middleware('admin');
Route::post('/importprogram', [ProgramController::class, 'importexcel'])->name('program.importexcel')->middleware('admin');

Route::resource('/dataprogramskpd', ProgramskpdController::class)->middleware('admin');
Route::post('/importprogramskpd', [ProgramskpdController::class, 'importexcel'])->name('programskpd.importexcel')->middleware('admin');

Route::resource('/datakegiatan', KegiatanController::class)->middleware('admin');
Route::post('/importkegiatan', [KegiatanController::class, 'importexcel'])->name('kegiatan.importexcel')->middleware('admin');

Route::resource('/datasubkegiatan', SubkegiatanController::class)->middleware('admin');
Route::post('/importsubkegiatan', [SubkegiatanController::class, 'importexcel'])->name('subkegiatan.importexcel')->middleware('admin');

Route::resource('/rekbelanja', BelanjaController::class)->middleware('admin');
Route::post('/importrekbelanja', [BelanjaController::class, 'importexcel'])->name('rekbelanja.importexcel')->middleware('admin');

Route::resource('/rekpendapatan', PendapatanController::class)->middleware('admin');
Route::post('/importrekpendapatan', [PendapatanController::class, 'importexcel'])->name('rekpendapatan.importexcel')->middleware('admin');

Route::resource('/dataurusan', UrusanController::class)->middleware('admin');
Route::post('/importurusan', [UrusanController::class, 'importexcel'])->name('urusan.importexcel')->middleware('admin');

Route::resource('/perekening', PerekeningController::class)->middleware('auth');
Route::post('/importperekening', [PerekeningController::class, 'importexcel'])->name('perekening.importexcel')->middleware('admin');

Route::resource('/relpendapatan', RelpendapatanController::class)->middleware('auth');
// Route::get('/relpendapatanxxx', [RelpendapatanController::class, 'xxx'])->name('relpendapatan.index_admin')->middleware('auth');
Route::post('/importrelpendapatan', [RelpendapatanController::class, 'importexcel'])->name('relpendapatan.importexcel')->middleware('admin');
// Route::get('/relpendapatan', RelpendapatanController::class)->middleware('auth');

Route::get('/total-anggaran', [PerekeningController::class, 'totalAnggaran']);


Route::get('/chart', [ChartController::class, 'index']);


// Route::get('/ajax', 'UserController@ajax');
// Route::post('/datauser', [UserController::class, 'ajax'])->name('datauser.ajax');
// Route::get('/datauser', [UserController::class, 'add']);

resources/views/dashboard.blade.php
@extends('layouts.main')
@section('judul', 'Dashboard')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                @can('admin')
                    <h1>Super Admin</h1>
                @elsecan('kepda')
                    <h1>Kepala Daerah</h1>
                @elsecan('user')
                    <h1> {{ $data->nm_skpd }}</h1>
                @endcan
            </div>
            <div class="row">
                <div class="col-12 col-md-6 col-lg-6">
                    <div class="card">
                        <div class="card-header">
                            <h4>Pendapatan</h4>
                        </div>
                        <div class="card-header">
                            <h4>Total Anggaran <span>@currency($pdptnanggaran)</span></h4>
                        </div>
                        <div class="card-body">
                            <canvas id="chartpendapatan"></canvas>
                        </div>
                        <div class="card-body">
                            <div class="card card-statistic-2 mb-0">
                                <div class="card-icon shadow-primary bg-danger">
                                    <i class="fas fa-dollar-sign"></i>
                                </div>
                                <div class="card-wrap">
                                    <div class="card-header">
                                        <h4>Belum Realisasi</h4>
                                    </div>
                                    <h6>
                                        @currency($data_blm_rel_pdptn)
                                    </h6>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="card card-statistic-2 mb-0">
                                <div class="card-icon shadow-primary bg-primary">
                                    <i class="fas fa-dollar-sign"></i>
                                </div>
                                <div class="card-wrap">
                                    <div class="card-header">
                                        <h4>Total Realisasi</h4>
                                    </div>
                                    <h6>
                                        @currency($pdptnrealisasi)
                                    </h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {{-- rekbelanja --}}
                <div class="col-12 col-md-6 col-lg-6">
                    <div class="card">
                        <div class="card-header">
                            <h4>Belanja</h4>
                        </div>
                        <div class="card-header">
                            <h4>Total Anggaran <span>@currency($blnjanggaran)</span> </h4>
                        </div>
                        <div class="card-body">
                            <canvas id="chartbelanja"></canvas>
                        </div>
                        <div class="card-body">
                            <div class="card card-statistic-2 mb-0">
                                <div class="card-icon shadow-primary bg-danger">
                                    <i class="fas fa-dollar-sign"></i>
                                </div>
                                <div class="card-wrap">
                                    <div class="card-header">
                                        <h4>Belum Realisasi</h4>
                                    </div>
                                    <h6>
                                        @currency($data_blm_rel_blnj)
                                    </h6>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="card card-statistic-2 mb-0">
                                <div class="card-icon shadow-primary bg-primary">
                                    <i class="fas fa-shopping-bag"></i>
                                </div>
                                <div class="card-wrap">
                                    <div class="card-header">
                                        <h4>Total Realisasi</h4>
                                    </div>
                                    <h6>
                                        @currency($blnjrealisasi)
                                    </h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="card card-statistic-1">
                        <div class="card-icon bg-primary">
                            <i class="far fa-user"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Program</h4>
                            </div>
                            <div class="card-body">
                                {{ $jml_program }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card card-statistic-1">
                        <div class="card-icon bg-danger">
                            <i class="far fa-newspaper"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Kegiatan</h4>
                            </div>
                            <div class="card-body">
                                {{ $jml_kegiatan }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="card card-statistic-1">
                        <div class="card-icon bg-warning">
                            <i class="far fa-file"></i>
                        </div>
                        <div class="card-wrap">
                            <div class="card-header">
                                <h4>Sub Kegiatan</h4>
                            </div>
                            <div class="card-body">
                                {{ $jml_subkegiatan }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/login.blade.php
@extends('layouts.auth')
@section('judul', 'Login')
@section('content')
    <!-- Main Content -->
    <div id="app">
        <section class="section">
            <div class="container mt-5">
                <div class="row">
                    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
                        <div class="login-brand">
                            <a href="#collapseExample" data-toggle="collapse">

                                <img src="../assets/img/stisla-fill.svg" alt="logo" width="100"
                                    class="shadow-light rounded-circle">
                            </a>
                        </div>
                        <div class="card card-danger">
                            <div class="collapse" id="collapseExample">
                                <div class="card-header">
                                    <h4 class="text-danger">Akun Demo</h4>
                                </div>

                                <div class="card-body pb-0">
                                    <table class="table table-responsive p-0">
                                        <thead>
                                            <tr>
                                                <th scope="col">Admin</th>
                                                <th scope="col">Email</th>
                                                <th scope="col">Password</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr class="m-0">
                                                <th scope="row">1</th>
                                                <td>Mark</td>
                                                <td>1234</td>
                                            </tr>
                                            <tr>
                                                <th scope="row">2</th>
                                                <td>Jacob</td>
                                                <td>1234</td>
                                            </tr>
                                            <tr>
                                                <th scope="row">3</th>
                                                <td>Larry</td>
                                                <td>1234</td>
                                            </tr>
                                            <tr>
                                                <th scope="row">4</th>
                                                <td>Larry</td>
                                                <td>1234</td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>
                            </div>

                            @if (session()->has('succes'))
                                <div class="alert alert-succes alert-dismissible fade show" role="alert">
                                    {{ session('success') }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">

                                    </button>

                                </div>
                            @endif
                            @if (session()->has('loginError'))
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    {{ session('loginError') }}
                                </div>
                            @endif

                            <div class="card-header pt-0">
                                <h4 class="text-danger">Login</h4>
                            </div>

                            <div class="card-body">
                                <form method="POST" action="/auth" novalidate="">
                                    @csrf
                                    <div class="form-group">
                                        <label for="email">Username</label>
                                        <input id="username" type="text"
                                            class="form-control @error('username') is-invalid @enderror" name="username"
                                            tabindex="1" required autofocus value="{{ old('username') }}">
                                        @error('username')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <div class="d-block">
                                            <label for="password" class="control-label">Password</label>
                                        </div>
                                        <input id="password" type="password"
                                            class="form-control @error('password') is-invalid @enderror" name="password"
                                            tabindex="2" required>
                                        @error('password')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-danger btn-lg btn-block" tabindex="4">
                                            Login
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="simple-footer">
                            Copyright &copy; 2018 <div class="bullet"></div> Simulasi Data <a href="https://google.id/"
                                class="text-danger">
                                Pemko Padang
                                <a href="regadmin" class="text-danger">
                                    Regis Akun
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/reg.blade.php
@extends('layouts.auth')
@section('judul', 'Daftar Admin')
@section('content')
    <!-- Main Content -->
    <div id="app">
        <section class="section">
            <div class="container mt-5">
                <div class="row">
                    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
                        <div class="login-brand">
                            <a href="#collapseExample" data-toggle="collapse">

                                <img src="../assets/img/stisla-fill.svg" alt="logo" width="100"
                                    class="shadow-light rounded-circle">
                            </a>
                        </div>
                        <div class="card card-danger">
                            <div class="card-header pt-0">
                                <h4 class="text-danger">Daftar Admin</h4>
                            </div>
                            <div class="card-body">
                                <form method="POST" action="/regadmin" novalidate="">
                                    @csrf
                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        <input id="username" type="text"
                                            class="form-control @error('username') is-invalid @enderror" name="username"
                                            tabindex="1" required autofocus value="{{ old('username') }}">
                                        @error('username')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <div class="d-block">
                                            <label for="password" class="control-label">Password</label>
                                        </div>
                                        <input id="password" type="password"
                                            class="form-control @error('password') is-invalid @enderror" name="password"
                                            tabindex="2" required>
                                        @error('password')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-danger btn-lg btn-block" tabindex="4">
                                            Registrasi Akun
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="simple-footer">
                            Copyright &copy; 2018 <div class="bullet"></div> Simulasi Data <a href="https://google.id/"
                                class="text-danger">
                                Pemko Padang
                                <a href="/login" class="text-danger">
                                    Sign In
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/user-data.blade.php
@extends('layouts.main')
@section('judul', 'Data User')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Data User</h1>
            </div>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button class="btn btn-primary rounded" data-toggle="modal" data-target="#ModalTambah">
                                    <i class="fas fa-plus mr-2"></i>
                                    Tambah User SKPD </button>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-biasa">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Nama Kadis</th>
                                                <th>NIP</th>
                                                <th>SKPD</th>
                                                <th>Username</th>
                                                <th>Aksi</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @php $no = 1; @endphp
                                            @foreach ($users as $row)
                                                <tr>
                                                    <td>{{ $no++ }}</td>
                                                    <td>{{ $row->name }}</td>
                                                    <td>{{ $row->nip }}</td>
                                                    <td>{{ $row->nm_skpd }}</td>
                                                    <td>{{ $row->username }}</td>
                                                    <td style="width: 350px">
                                                        <div class="d-inline-block">
                                                            <a href="#" data-target="#ModalLihat{{ $row->id }}"
                                                                class="btn btn-info" data-toggle="modal"> <i
                                                                    class="fas fa-eye"></i> Lihat</a>
                                                            <a href="{{ route('datauser.edit', $row->id) }}"
                                                                class="btn btn-warning"> <i class="fas fa-eye"></i>
                                                                Edit</a>
                                                            <button class="btn btn-danger" data-toggle="modal"
                                                                data-target="#ModalHapus">
                                                                <i class="fas fa-trash"></i>
                                                                Hapus </button>
                                                        </div>

                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {{-- modalTambah --}}
        <div class="modal fade" role="dialog" id="ModalTambah">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Tambah User SKPD</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card-body">
                            <form method="POST" action="/datauser" class="needs-validation">
                                @csrf
                                @method('POST')
                                <div class="form-group">
                                    <label for="name">Nama Kepala Dinas</label>
                                    <input id="name" type="text"
                                        class="@error('name') is-invalid @enderror form-control" name="name"
                                        tabindex="1" value="{{ old('name') }}" required autofocus>
                                </div>
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input id="username" type="text"
                                        class="@error('username') is-invalid @enderror form-control" name="username"
                                        tabindex="1" value="{{ old('username') }}" required autofocus>
                                    @error('username')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <div class="d-block">
                                        <label for="password" class="control-label">Password</label>
                                    </div>
                                    <input id="password" type="password"
                                        class="@error('password') is-invalid @enderror form-control" name="password"
                                        tabindex="2" required>
                                    <div class="invalid-feedback">
                                        please fill in your password
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="skpd">Nama SKPD</label>
                                    <select class="form-control select2" id="skpd" name="skpd">
                                        @foreach ($skpds as $row)
                                            <option value="{{ $row->id }}">{{ $row->nm_skpd }}</option>
                                        @endforeach

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="nip">NIP</label>
                                    <input id="nip" type="number"
                                        class="@error('nip') is-invalid @enderror form-control" name="nip"
                                        tabindex="1" value="{{ old('nip') }}" required autofocus>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                                        Simpan
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{-- endmodalTambah --}}

        {{-- modalLihat --}}
        @foreach ($users as $row)
            <div class="modal fade" tabindex="-1" role="dialog" id="ModalLihat{{ $row->id }}">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Data Detil</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="row">
                            <div class="col-md-6 ml-4">
                                <address>
                                    <strong>Nama :</strong><br>
                                    {{ $row->name }}<br>
                                </address>
                                <address>
                                    <strong>NIP :</strong><br>
                                    {{ $row->nip }}<br>
                                </address>
                                <address>
                                    <strong>SKPD :</strong><br>
                                    {{ $row->nm_skpd }}<br>
                                </address>
                            </div>
                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        {{-- endmodalLihat --}}
    </div>
@endsection