routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkpdController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UrusanController;
use App\Http\Controllers\BelanjaController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\KegiatanController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;

use App\Http\Controllers\PendapatanController;
use App\Http\Controllers\PerekeningController;
use App\Http\Controllers\ProgramskpdController;
use App\Http\Controllers\SubkegiatanController;
use App\Http\Controllers\RelpendapatanController;

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/auth', [LoginController::class, 'auth'])->name('auth')->middleware('guest');


Route::post('/logout', [LoginController::class, 'logout'])->middleware('auth');


Route::get('/regadmin', [RegisterController::class, 'index'])->middleware('guest');
Route::post('/regadmin', [RegisterController::class, 'store']);

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth');
Route::get('/data-json', [DashboardController::class, 'datajson'])->middleware('guest');
Route::get('/get-json', [DashboardController::class, 'getjson'])->middleware('guest');


Route::resource('/datauser', UserController::class)->middleware('admin');

Route::resource('/dataskpd', SkpdController::class)->middleware('admin');
Route::post('/importskpd', [SkpdController::class, 'importexcel'])->name('importexcel')->middleware('admin'); //tambah class skpd

Route::resource('/dataprogram', ProgramController::class)->middleware('admin');
Route::post('/importprogram', [ProgramController::class, 'importexcel'])->name('program.importexcel')->middleware('admin');

Route::resource('/dataprogramskpd', ProgramskpdController::class)->middleware('admin');
Route::post('/importprogramskpd', [ProgramskpdController::class, 'importexcel'])->name('programskpd.importexcel')->middleware('admin');

Route::resource('/datakegiatan', KegiatanController::class)->middleware('admin');
Route::post('/importkegiatan', [KegiatanController::class, 'importexcel'])->name('kegiatan.importexcel')->middleware('admin');

Route::resource('/datasubkegiatan', SubkegiatanController::class)->middleware('admin');
Route::post('/importsubkegiatan', [SubkegiatanController::class, 'importexcel'])->name('subkegiatan.importexcel')->middleware('admin');

Route::resource('/rekbelanja', BelanjaController::class)->middleware('admin');
Route::post('/importrekbelanja', [BelanjaController::class, 'importexcel'])->name('rekbelanja.importexcel')->middleware('admin');

Route::resource('/rekpendapatan', PendapatanController::class)->middleware('admin');
Route::post('/importrekpendapatan', [PendapatanController::class, 'importexcel'])->name('rekpendapatan.importexcel')->middleware('admin');

Route::resource('/dataurusan', UrusanController::class)->middleware('admin');
Route::post('/importurusan', [UrusanController::class, 'importexcel'])->name('urusan.importexcel')->middleware('admin');

Route::resource('/perekening', PerekeningController::class)->middleware('auth');
Route::post('/importperekening', [PerekeningController::class, 'importexcel'])->name('perekening.importexcel')->middleware('admin');

Route::resource('/relpendapatan', RelpendapatanController::class)->middleware('auth');
// Route::get('/relpendapatanxxx', [RelpendapatanController::class, 'xxx'])->name('relpendapatan.index_admin')->middleware('auth');
Route::post('/importrelpendapatan', [RelpendapatanController::class, 'importexcel'])->name('relpendapatan.importexcel')->middleware('admin');
// Route::get('/relpendapatan', RelpendapatanController::class)->middleware('auth');

Route::get('/total-anggaran', [PerekeningController::class, 'totalAnggaran']);


Route::get('/chart', [ChartController::class, 'index']);


// Route::get('/ajax', 'UserController@ajax');
// Route::post('/datauser', [UserController::class, 'ajax'])->name('datauser.ajax');
// Route::get('/datauser', [UserController::class, 'add']);

resources/views/tabel/kegiatan.blade.php
@extends('layouts.main')
@section('judul', 'Data Kegiatan')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Data Kegiatan</h1>
            </div>
            <div class="section-body">
                <h2 class="section-title">Example Title</h2>
                <p class="section-lead">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae, ipsa.
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button class="btn btn-primary rounded-1" data-toggle="modal" data-target="#exampleModal">
                                    Import Excel
                                </button>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-kegiatan">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Id Kegiatan</th>
                                                <th>Nama Kegiatan</th>
                                                <th>Nu Kegiatan</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="/importkegiatan" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="modal-body">
                            <div class="form-group">
                                <input type="file" name="file" required>
                            </div>
                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/tabel/perekening.blade.php
@extends('layouts.main')
@section('judul', 'Data Belanja')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                @php
                    $user = auth()->user();
                    if ($user->skpd === null) {
                        echo '<h1>Kepala Daerah</h1>';
                    } else {
                        echo '<h1>' . $data_user->nm_skpd . '</h1>';
                    }
                @endphp
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            @can('admin')
                                <div class="card-header">
                                    <button class="btn btn-primary rounded-1" data-toggle="modal" data-target="#exampleModal">
                                        Import Excel
                                    </button>
                                </div>
                            @endcan
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-perekening" style="width:100%">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Nama SKPD</th>
                                                <th>Program</th>
                                                <th>Kegiatan</th>
                                                <th>Sub Kegiatan</th>
                                                <th>Kode Rekening</th>
                                                <th>Nama Rekening</th>
                                                <th>Anggaran</th>
                                                <th>Realisasi</th>
                                                <th>Sisa Anggaran</th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                                <th>Total</th>
                                                <th>Anggaran</th>
                                                <th>Realisasi</th>
                                                <th>Sisa Anggaran</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class=" modal fade" tabindex="-1" role="dialog" id="exampleModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="/importperekening" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="modal-body">
                            <div class="form-group">
                                <input type="file" name="file" required>
                            </div>
                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/tabel/program.blade.php
@extends('layouts.main')
@section('judul', 'Data Program')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Data Program</h1>
            </div>
            <div class="section-body">
                <h2 class="section-title">Example Title</h2>
                <p class="section-lead">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae, ipsa.
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button class="btn btn-primary rounded-1" data-toggle="modal" data-target="#exampleModal">
                                    Import Excel
                                </button>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-program">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Id Program</th>
                                                <th>Unit Key</th>
                                                <th>Nama Program</th>
                                                <th>Nu Program</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="/importprogram" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="modal-body">
                            <div class="form-group">
                                <input type="file" name="file" required>
                            </div>
                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/tabel/programskpd.blade.php
@extends('layouts.main')
@section('judul', 'Data Program SKPD')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Data Program SKPD</h1>
            </div>
            <div class="section-body">
                <h2 class="section-title">Example Title</h2>
                <p class="section-lead">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae, ipsa.
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button class="btn btn-primary rounded-1" data-toggle="modal" data-target="#exampleModal">
                                    Import Excel
                                </button>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-programskpd">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Nama SKPD</th>
                                                <th>Id Program</th>
                                                <th>Nama Program</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="/importprogramskpd" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="modal-body">
                            <div class="form-group">
                                <input type="file" name="file" required>
                            </div>
                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/tabel/skpd.blade.php
@extends('layouts.main')
@section('judul', 'Data Skpd')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Data SKPD</h1>
            </div>
            <div class="section-body">
                <h2 class="section-title">Example Title</h2>
                <p class="section-lead">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae, ipsa.
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button class="btn btn-primary rounded-1" data-toggle="modal" data-target="#exampleModal">
                                    Import Excel
                                </button>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-biasa">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Unit Key</th>
                                                <th>Kode Unit</th>
                                                <th>Nama SKPD</th>
                                                <th>Level SKPD</th>
                                                <th>Type</th>
                                                <th>Aksi</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @php $no = 1; @endphp
                                            @foreach ($skpds as $row)
                                                <tr>
                                                    <td>{{ $no++ }}</td>
                                                    <td>{{ $row->unit_key }}</td>
                                                    <td>{{ $row->kode_skpd }}</td>
                                                    <td>{{ $row->nm_skpd }}</td>
                                                    <td>{{ $row->lv_id }}</td>
                                                    <td>{{ $row->type }}</td>
                                                    <td style="width: 350px">
                                                        <div class="d-inline-block">
                                                            <a href="{{ route('dataskpd.edit', $row->id) }}"
                                                                class="btn btn-warning"> <i class="fas fa-eye"></i>
                                                                Edit</a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="/importskpd" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="modal-body">
                            <div class="form-group">
                                <input type="file" name="file" required>
                            </div>
                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                </div>
                </form>
            </div>
        </div>

        {{-- modalTambah --}}
        <div class="modal fade" role="dialog" id="ModalTambah">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Tambah Data SKPD</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card-body">
                            <form method="POST" action="{{ route('dataskpd.store') }}" class="needs-validation">
                                @csrf
                                @method('POST')
                                <div class="form-group">
                                    <label for="unit_key">Unit Key</label>
                                    <input id="unit_key" type="text"
                                        class="@error('unit_key') is-invalid @enderror form-control" name="unit_key"
                                        tabindex="1" value="{{ old('unit_key') }}" required autofocus>
                                </div>
                                <div class="form-group">
                                    <label for="kode_skpd">Kode SKPD</label>
                                    <input id="kode_skpd" type="text"
                                        class="@error('kode_skpd') is-invalid @enderror form-control" name="kode_skpd"
                                        tabindex="1" value="{{ old('kode_skpd') }}" required autofocus>
                                    @error('kode_skpd')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="nm_skpd">Nama SKPD</label>
                                    <input id="nm_skpd" type="text"
                                        class="@error('nm_skpd') is-invalid @enderror form-control" name="nm_skpd"
                                        tabindex="1" value="{{ old('nm_skpd') }}" required autofocus>
                                    @error('nm_skpd')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="lv_id">Id Level</label>
                                    <input id="lv_id" type="text"
                                        class="@error('lv_id') is-invalid @enderror form-control" name="lv_id"
                                        tabindex="1" value="{{ old('lv_id') }}" required autofocus>
                                    @error('lv_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="type">Type</label>
                                    <input id="type" type="text"
                                        class="@error('type') is-invalid @enderror form-control" name="type"
                                        tabindex="1" value="{{ old('type') }}" required autofocus>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                                        Simpan
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{-- endmodalTambah --}}
    </div>
@endsection

resources/views/tabel/subkegiatan.blade.php
@extends('layouts.main')
@section('judul', 'Data Sub Kegiatan')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Data Sub Kegiatan</h1>
            </div>
            <div class="section-body">
                <h2 class="section-title">Example Title</h2>
                <p class="section-lead">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae, ipsa.
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <button class="btn btn-primary rounded-1" data-toggle="modal" data-target="#exampleModal">
                                    Import Excel
                                </button>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped" id="table-subkegiatan">
                                        <thead>
                                            <tr>
                                                <th>No</th>
                                                <th>Unit Key</th>
                                                <th>Kode Sub Kegiatan</th>
                                                <th>Nama Sub Kegiatan</th>
                                                <th>Nama SKPD</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="modal fade" tabindex="-1" role="dialog" id="exampleModal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="/importsubkegiatan" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="modal-body">
                            <div class="form-group">
                                <input type="file" name="file" required>
                            </div>
                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
@endsection