routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkpdController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UrusanController;
use App\Http\Controllers\BelanjaController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\KegiatanController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;

use App\Http\Controllers\PendapatanController;
use App\Http\Controllers\PerekeningController;
use App\Http\Controllers\ProgramskpdController;
use App\Http\Controllers\SubkegiatanController;
use App\Http\Controllers\RelpendapatanController;

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/auth', [LoginController::class, 'auth'])->name('auth')->middleware('guest');


Route::post('/logout', [LoginController::class, 'logout'])->middleware('auth');


Route::get('/regadmin', [RegisterController::class, 'index'])->middleware('guest');
Route::post('/regadmin', [RegisterController::class, 'store']);

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth');
Route::get('/data-json', [DashboardController::class, 'datajson'])->middleware('guest');
Route::get('/get-json', [DashboardController::class, 'getjson'])->middleware('guest');


Route::resource('/datauser', UserController::class)->middleware('admin');

Route::resource('/dataskpd', SkpdController::class)->middleware('admin');
Route::post('/importskpd', [SkpdController::class, 'importexcel'])->name('importexcel')->middleware('admin'); //tambah class skpd

Route::resource('/dataprogram', ProgramController::class)->middleware('admin');
Route::post('/importprogram', [ProgramController::class, 'importexcel'])->name('program.importexcel')->middleware('admin');

Route::resource('/dataprogramskpd', ProgramskpdController::class)->middleware('admin');
Route::post('/importprogramskpd', [ProgramskpdController::class, 'importexcel'])->name('programskpd.importexcel')->middleware('admin');

Route::resource('/datakegiatan', KegiatanController::class)->middleware('admin');
Route::post('/importkegiatan', [KegiatanController::class, 'importexcel'])->name('kegiatan.importexcel')->middleware('admin');

Route::resource('/datasubkegiatan', SubkegiatanController::class)->middleware('admin');
Route::post('/importsubkegiatan', [SubkegiatanController::class, 'importexcel'])->name('subkegiatan.importexcel')->middleware('admin');

Route::resource('/rekbelanja', BelanjaController::class)->middleware('admin');
Route::post('/importrekbelanja', [BelanjaController::class, 'importexcel'])->name('rekbelanja.importexcel')->middleware('admin');

Route::resource('/rekpendapatan', PendapatanController::class)->middleware('admin');
Route::post('/importrekpendapatan', [PendapatanController::class, 'importexcel'])->name('rekpendapatan.importexcel')->middleware('admin');

Route::resource('/dataurusan', UrusanController::class)->middleware('admin');
Route::post('/importurusan', [UrusanController::class, 'importexcel'])->name('urusan.importexcel')->middleware('admin');

Route::resource('/perekening', PerekeningController::class)->middleware('auth');
Route::post('/importperekening', [PerekeningController::class, 'importexcel'])->name('perekening.importexcel')->middleware('admin');

Route::resource('/relpendapatan', RelpendapatanController::class)->middleware('auth');
// Route::get('/relpendapatanxxx', [RelpendapatanController::class, 'xxx'])->name('relpendapatan.index_admin')->middleware('auth');
Route::post('/importrelpendapatan', [RelpendapatanController::class, 'importexcel'])->name('relpendapatan.importexcel')->middleware('admin');
// Route::get('/relpendapatan', RelpendapatanController::class)->middleware('auth');

Route::get('/total-anggaran', [PerekeningController::class, 'totalAnggaran']);


Route::get('/chart', [ChartController::class, 'index']);


// Route::get('/ajax', 'UserController@ajax');
// Route::post('/datauser', [UserController::class, 'ajax'])->name('datauser.ajax');
// Route::get('/datauser', [UserController::class, 'add']);

app/Models/Skpd.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Urusan;
use App\Models\Perekening;
use App\Models\Programskpd;
use App\Models\Subkegiatan;
use App\Models\Relpendapatan;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Skpd extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function perekening()
    {
        return $this->hasMany(Perekening::class);  // 1 skpd, bisa bnyak perekening
    }
    public function relpendapatan()
    {
        return $this->hasMany(Relpendapatan::class);  // 1 skpd, bisa bnyak relpendapatan
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'id'); // 1 skpd, hanya 1 user 
    }


    // salah
    public function urusan()
    {
        return $this->hasMany(Urusan::class);  // 1 skpd, bisa bnyak urusan
    }

    public function programskpd()
    {
        return $this->hasMany(Programskpd::class);  // 1 skpd, bisa bnyak programskpd
    }

    public function subkegiatan()
    {
        return $this->hasMany(Subkegiatan::class);  // 1 skpd, bisa bnyak subkegiatan
    }
}

app/Http/Controllers/SkpdController.php
<?php

namespace App\Http\Controllers;

use App\Models\Skpd;
use App\Imports\SkpdImport;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Routing\Controller;
use Maatwebsite\Excel\Facades\Excel;

class SkpdController extends Controller
{
    public function indexx(Request $request)
    {
        $data = Skpd::join('kadis', 'skpds.lv_id', '=', 'kadis.id')
            ->select([
                'skpds.*',
                'kadis.*',
            ]);


        // $ddd = DataTables::of($data)->make(true);
        // dd($data);

        // echo '<pre>';
        // print_r($data);
        // die;




        // $posts = Skpd::latest()->get();
        // echo '<pre>';
        // print_r($posts);
        // die;

        if ($request->ajax()) {
            return DataTables::of($data)->make(true);
        }
        return view('tabel.skpd');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate(
            [
                'unit_key' => 'required',
                'kode_skpd' => 'required',
                'nm_skpd' => 'required',
                'lv_id' => 'required',
                'type' => 'required'
            ],
            [
                'unit_key.required' => 'Harus diisi',
                'kode_skpd.required' => 'Harus diisi',
            ]
        );
        // dd($validatedData);
        Skpd::create($validatedData);


        if ($validatedData) {
            return back()->with('success', 'Success! Skpd created');
        } else {
            return back()->with('error', 'Failed! Skpd not created');
        }
    }

    public function edit($id)
    {
        $skpd = Skpd::findOrFail($id);
        // $skpds = Skpd::latest()->get();

        return view('skpd.edit', compact('skpd'));
    }

    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'unit_key' => 'required',
            'kode_skpd' => 'required',
            'nm_skpd' => 'required',
            'lv_id' => 'required',
            'type' => 'required'
        ]);
        Skpd::whereId($id)->update($validatedData);

        return redirect('/dataskpd')->with('success', 'Game Data is successfully updated');
    }

    public function index()
    {

        // echo 'xxx';
        // die;
        $skpds = Skpd::latest()->get();
        // echo '<pre>';
        // print_r($skpds);
        // die;

        return view('tabel.skpd', compact(['skpds']));
    }


    public function importexcel(Request $request)
    {
        // $this->validate(
        //     $request,
        //     [
        //         'file' => 'required|mimes:xls,xlsx'
        //     ]
        // );

        // $path = $request->file('file')->getRealPath();
        // $data = Excel::load($path)->get();

        // dd($data);


        $data = $request->file('file');

        $namafile = $data->getClientOriginalName();
        $data->move('SkpdData', $namafile);

        Excel::import(new SkpdImport, \public_path('/SkpdData/' . $namafile));
        return redirect()->back();
    }

    public function ajax(Request $request)
    {
        $input = $request->all();

        if (!empty($input['query'])) {

            $data = Skpd::select(["id", "nm_skpd"])
                ->where("nm_skpd", "LIKE", "%{$input['query']}%")
                ->get();
        } else {

            $data = Skpd::select(["id", "nm_skpd"])
                ->get();
        }

        $skpds = [];

        if (count($data) > 0) {

            foreach ($data as $row) {
                $skpds[] = array(
                    "id" => $row->id,
                    "text" => $row->nm_skpd,
                );
            }
        }

        return response()->json($skpds);
    }
}

resources/views/skpd/edit.blade.php
{{-- {{ $user-id }} --}}
@extends('layouts.main')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Edit SKPD</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-8 mx-auto">
                        <div class="card">
                            <div class="card-header">
                                <h4>Edit Data SKPD </h4>
                            </div>
                            <div class="card-body">
                                <form method="POST" action="{{ route('dataskpd.update', $skpd->id) }}"
                                    class="needs-validation">
                                    @csrf
                                    @method('PATCH')
                                    <div class="form-group">
                                        <label for="unit_key">Unit Key</label>
                                        <input id="unit_key" type="text"
                                            class="@error('unit_key') is-invalid @enderror form-control" name="unit_key"
                                            tabindex="1" value="{{ old('unit_key', $skpd->unit_key) }}" required
                                            autofocus>
                                    </div>
                                    <div class="form-group">
                                        <label for="kode_skpd">Kode SKPD</label>
                                        <input id="kode_skpd" type="text"
                                            class="@error('kode_skpd') is-invalid @enderror form-control" name="kode_skpd"
                                            tabindex="1" value="{{ old('kode_skpd', $skpd->kode_skpd) }}" required
                                            autofocus>
                                        @error('kode_skpd')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="nm_skpd">Nama SKPD</label>
                                        <input id="nm_skpd" type="text"
                                            class="@error('nm_skpd') is-invalid @enderror form-control" name="nm_skpd"
                                            tabindex="1" value="{{ old('nm_skpd', $skpd->nm_skpd) }}" required autofocus>
                                        @error('nm_skpd')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="lv_id">Id Level</label>
                                        <input id="lv_id" type="text"
                                            class="@error('lv_id') is-invalid @enderror form-control" name="lv_id"
                                            tabindex="1" value="{{ old('lv_id', $skpd->lv_id) }}" required autofocus>
                                        @error('lv_id')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="type">Type</label>
                                        <input id="type" type="text"
                                            class="@error('type') is-invalid @enderror form-control" name="type"
                                            tabindex="1" value="{{ old('type', $skpd->type) }}" required autofocus>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                                            Simpan
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection