routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SkpdController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ChartController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UrusanController;
use App\Http\Controllers\BelanjaController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\KegiatanController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DashboardController;

use App\Http\Controllers\PendapatanController;
use App\Http\Controllers\PerekeningController;
use App\Http\Controllers\ProgramskpdController;
use App\Http\Controllers\SubkegiatanController;
use App\Http\Controllers\RelpendapatanController;

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/auth', [LoginController::class, 'auth'])->name('auth')->middleware('guest');


Route::post('/logout', [LoginController::class, 'logout'])->middleware('auth');


Route::get('/regadmin', [RegisterController::class, 'index'])->middleware('guest');
Route::post('/regadmin', [RegisterController::class, 'store']);

Route::get('/dashboard', [DashboardController::class, 'index'])->middleware('auth');
Route::get('/data-json', [DashboardController::class, 'datajson'])->middleware('guest');
Route::get('/get-json', [DashboardController::class, 'getjson'])->middleware('guest');


Route::resource('/datauser', UserController::class)->middleware('admin');

Route::resource('/dataskpd', SkpdController::class)->middleware('admin');
Route::post('/importskpd', [SkpdController::class, 'importexcel'])->name('importexcel')->middleware('admin'); //tambah class skpd

Route::resource('/dataprogram', ProgramController::class)->middleware('admin');
Route::post('/importprogram', [ProgramController::class, 'importexcel'])->name('program.importexcel')->middleware('admin');

Route::resource('/dataprogramskpd', ProgramskpdController::class)->middleware('admin');
Route::post('/importprogramskpd', [ProgramskpdController::class, 'importexcel'])->name('programskpd.importexcel')->middleware('admin');

Route::resource('/datakegiatan', KegiatanController::class)->middleware('admin');
Route::post('/importkegiatan', [KegiatanController::class, 'importexcel'])->name('kegiatan.importexcel')->middleware('admin');

Route::resource('/datasubkegiatan', SubkegiatanController::class)->middleware('admin');
Route::post('/importsubkegiatan', [SubkegiatanController::class, 'importexcel'])->name('subkegiatan.importexcel')->middleware('admin');

Route::resource('/rekbelanja', BelanjaController::class)->middleware('admin');
Route::post('/importrekbelanja', [BelanjaController::class, 'importexcel'])->name('rekbelanja.importexcel')->middleware('admin');

Route::resource('/rekpendapatan', PendapatanController::class)->middleware('admin');
Route::post('/importrekpendapatan', [PendapatanController::class, 'importexcel'])->name('rekpendapatan.importexcel')->middleware('admin');

Route::resource('/dataurusan', UrusanController::class)->middleware('admin');
Route::post('/importurusan', [UrusanController::class, 'importexcel'])->name('urusan.importexcel')->middleware('admin');

Route::resource('/perekening', PerekeningController::class)->middleware('auth');
Route::post('/importperekening', [PerekeningController::class, 'importexcel'])->name('perekening.importexcel')->middleware('admin');

Route::resource('/relpendapatan', RelpendapatanController::class)->middleware('auth');
// Route::get('/relpendapatanxxx', [RelpendapatanController::class, 'xxx'])->name('relpendapatan.index_admin')->middleware('auth');
Route::post('/importrelpendapatan', [RelpendapatanController::class, 'importexcel'])->name('relpendapatan.importexcel')->middleware('admin');
// Route::get('/relpendapatan', RelpendapatanController::class)->middleware('auth');

Route::get('/total-anggaran', [PerekeningController::class, 'totalAnggaran']);


Route::get('/chart', [ChartController::class, 'index']);


// Route::get('/ajax', 'UserController@ajax');
// Route::post('/datauser', [UserController::class, 'ajax'])->name('datauser.ajax');
// Route::get('/datauser', [UserController::class, 'add']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $guarded = ['id'];

    // protected $fillable = [
    //     // 'name',
    //     // 'email',
    //     'username',
    //     'password',
    // ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Skpd;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {

        $users = User::join('skpds', 'users.skpd', '=', 'skpds.id')
            ->get([
                'users.*',
                'skpds.*'
            ]);

        $skpds = DB::table('skpds')->whereIn('lv_id', array(3))->get();


        // dd($skpds);

        return view('user-data', compact('users', 'skpds'));
    }

    // public function ajax(Request $request)
    // {
    //     $search = $request->search;
    //     // $search = 'dinas';

    //     if ($search == '') {
    //         $employees = Skpd::orderby('nm_skpd', 'asc')->select('id', 'nm_skpd')->limit(5)->get();
    //     } else {
    //         $employees = Skpd::orderby('nm_skpd', 'asc')->select('id', 'nm_skpd')->where('nm_skpd', 'like', '%' . $search . '%')->limit(5)->get();
    //     }

    //     $response = array();
    //     foreach ($employees as $employee) {
    //         $response[] = array(
    //             'id' => $employee->id,
    //             'text' => $employee->nm_skpd
    //         );
    //     }
    //     // return view('user-data', compact('response'));


    //     // dd($response);
    //     return response()->json($response);
    // }

    public function store(Request $request)
    {
        $validatedData = $request->validate(
            [
                'username' => 'required|unique:users',
                'password' => 'required',
                'name' => 'required',
                'skpd' => 'required',
                'nip' => 'required'
            ],
            [
                'username.required' => 'Harus diisi',
                'username.unique' => 'Username sudah ada',
            ]
        );
        $validatedData['password'] = Hash::make($validatedData['password']);

        // dd($validatedData);
        User::create($validatedData);


        if ($validatedData) {
            return back()->with('success', 'Success! User created');
        } else {
            return back()->with('error', 'Failed! User not created');
        }
    }

    public function show($id)
    {
        $id = 1;
        $user = DB::table('users')->where('id', $id)->first();

        // dd($user);

        // $user = User::find($id);
        // $userdata = User::latest()->get();
        // dd($userdata);
        return view('user-data', compact('user'));
    }

    public function edit($id)
    {

        $user = User::findOrFail($id);
        $skpds = Skpd::latest()->get();

        return view('user.edit', compact(['user', 'skpds']));
    }

    public function update(Request $request, $id)
    {
        // dd($request->all());
        $validatedData = $request->validate([
            'username' => 'required',
            'password' => 'required',
            'name' => 'required',
            'skpd_id' => 'required',
            'nip' => 'required'
        ]);
        User::whereId($id)->update($validatedData);

        return redirect('/datauser')->with('success', 'Game Data is successfully updated');



        // return view('user-data');

        // dd($request->all());
        // $user = User::findOrFail($user->id);



        // $dataskpd = Skpd::all();

        // $validatedData = $request->validate(
        //     [
        //         'username' => 'required',
        //         'password' => 'required',
        //         'name' => 'required',
        //         'skpd_id' => 'required',
        //         'nip' => 'required'
        //     ],
        //     [
        //         'username.required' => 'Harus diisi',
        //     ]
        // );
        // User::whereId($id)->update($validatedData);


        // if ($validatedData) {
        //     return redirect('datauser')->with('success', 'Success! User created');
        // } else {
        //     return redirect('datauser')->with('error', 'Failed! User not created');
        // }
    }


    // public function index()
    // {
    //     if(request()->ajax()) {
    //         return datatables()->of(Company::select('*'))
    //         ->addColumn('action', 'company-action')
    //         ->rawColumns(['action'])
    //         ->addIndexColumn()
    //         ->make(true);
    //     }
    //     return view('companies');
    // }


}

resources/views/user/edit.blade.php
@extends('layouts.main')
@section('content')
    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Edit User</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-8 mx-auto">
                        <div class="card">
                            <div class="card-header">
                                <h4>Edit Data </h4>
                            </div>
                            <div class="card-body">
                                <form method="POST" action="{{ route('datauser.update', $user->id) }}"
                                    class="needs-validation">
                                    @csrf
                                    @method('PATCH')
                                    <div class="form-group">
                                        <label for="name">Nama Kepala Dinas</label>
                                        <input id="name" type="text"
                                            class="@error('name') is-invalid @enderror form-control" name="name"
                                            tabindex="1" value="{{ $user->name }}" required autofocus>
                                    </div>
                                    <div class="form-group">
                                        <label for="username">Username</label>
                                        <input id="username" type="text"
                                            class="@error('username') is-invalid @enderror form-control" name="username"
                                            tabindex="1" value="{{ $user->username }}" required autofocus>
                                        @error('username')
                                            <div class="invalid-feedback">
                                                {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <div class="d-block">
                                            <label for="password" class="control-label">Password</label>
                                        </div>
                                        <input id="password" type="password"
                                            class="@error('password') is-invalid @enderror form-control" name="password"
                                            tabindex="2" required>
                                        <div class="invalid-feedback">
                                            please fill in your password
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="skpd">Nama SKPD</label>
                                        <select class="form-control select2" id="skpd" name="skpd_id" required>
                                            <option value="">Pilih Data SKPD</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="nip">NIP</label>
                                        <input id="nip" type="number"
                                            class="@error('nip') is-invalid @enderror form-control" name="nip"
                                            tabindex="1" value="{{ $user->nip }}" required autofocus>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                                            Simpan
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection